greenpeace/planet4-plugin-blocks

includes/settings.twig
Removed the settings for managing the blocks in the Blocks menu as it is not in requirements.
Kept the changes in a separate feature/manage-blocks branch for possible future usage.
=> Remove settings for managing blocks.

classes/controller/blocks/class-p4bks-blocks-splittwocolumns-controller.php
Fixes issue with selecting also pages other than the Issue pages (e.g. Take Action pages which have as parent page the Issue page).
=> Feature/1310 Block: Split Two Columns - update

classes/controller/blocks/class-p4bks-blocks-controller.php
- Adds a conditional to P4BKS_Blocks_Controller shortcode registration so we can render differently on preview
- Adds an iframe render method to render the shortcode via iframe in markup
- Adds a iframe ajax callback to render the markup defined by the preview iframe with html wrapper markup + site frontend scripts and styles
This is pretty hacky but looks to me like the best way to drop in the admin preview capability without either generating new admin script and style sheets specifically for these previews or having to modify existing functionality in the each registered block's prepare_template method.
see https://jira.greenpeace.org/browse/PLANET-1413
**Before**
**After**
Will require some continued work/testing during development of these modules and frontend styling to give good …
=> 1413 Post edit screen preview for shortcake blocks

planet4-blocks.php
Important: This update needs to run at the same time as the planet4-base update that uses the "wpackagist-plugin/shortcode-ui": "0.7.3" for pulling the shortcake plugin.
=> Switching directories so that we can pull the shortcake from wpackagist

classes/controller/blocks/class-contentfourcolumn-controller.php
Replaced p4-page-type select box with checkboxes in content four column block.
Made Publication post type selected by default.
Fixed bug when both p4-page-type and tag were selected.
=> Replaced p4-page-type select box with checkboxes.

classes/controller/blocks/class-contentfourcolumn-controller.php
Set all checkboxes in content four column as false/unchecked.
If you try to re-edit the block in the post editor it always appears the _publication_ checkbox as checked.
=> Remove setting publication post type as default. 

classes/controller/blocks/class-carouselsplit-controller.php, includes/blocks/carousel_split.twig
Use full wordpress image size for it's images and srcset generated by wordpress.
=> Remove timber resizing from carousel split block.

includes/blocks/covers.twig
Changes to covers markup regarding issues 90, 92 in feedback spreadsheet.
Remove css class from covers block top element. 
Wrap each cover/card in boostrap column to match presentation layer.
=> Update covers block markup

includes/blocks/carousel_header.twig
Remove assignment of 'next' class to 2nd slide during initial loading as it results in 2nd slide's header & subheader text blending with 1st slide's header & subheader (opacity: 1 set by css).
Sliding and wrapping functionality is not impaired.
=> Remove next css class assignment in second slide for styling reasons.

includes/blocks/content_three_column.twig
Show three-column-info div in content three column block only if title or description is set.
Addresses part of issue 167 in feedback spreadsheet.
=> Three-column-info div in content three column block

includes/blocks/static_four_column.twig
Apply the latest markup to static four column block to make images and titles clickable.
[Issue 1623](https://jira.greenpeace.org/browse/PLANET-1623)
=> Static four column images and titles clickable

includes/blocks/split_two_columns.twig
A minor markup change based on design fixes at greenpeace/planet4-presentation-layer#196
=> Button on split-two-columns-block should be btn-small

includes/blocks/covers.twig
Cover cards need to be inside `col-*` to follow the grid paddings.
=> Fix covers grid

classes/controller/blocks/class-splittwocolumns-controller.php
[Issue 1650](https://jira.greenpeace.org/browse/PLANET-1650)
Added optional fields for issue title, issue description, issue link, issue image and campaign image.
Changed select_tag to a simple select field because of an [issue](https://github.com/wp-shortcake/shortcake/issues/775) with select2 fields in shortcake (v. 0.7.3)
=> Added optional fields in split two column block

includes/blocks/covers.twig, includes/blocks/take_action_boxout.twig
This are the new gradient changes per designers feedback. We are removing gradients from cover cards passive and will have gradients only on hover.
Relevant frontend PR: greenpeace/planet4-presentation-layer#208
=> Remove cover cards gradient on passive state

classes/controller/blocks/class-covers-controllers.php
After discussing with product owner we decided to make use of the built in functionality wp offers for this task. So, we sort take action covers by the built-in Order field. Editors can set this field to make the covers appear with the exact same order they appear inside the Pages tab.
=> 1634 action covers sort

classes/controller/blocks/class-takeactionboxout-controllers.php
This for the "take action" cards on Posts. Currently these display the tag slug instead of the tag name.
This is per this [comment](https://jira.greenpeace.org/browse/PLANET-1581?focusedCommentId=61352&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-61352).
=> Sow tag name on action cards instead of slug

classes/controller/blocks/class-splittwocolumns-controller.php
and there is no defined title, the issue name appears with the special characters broken. This fixes that problem
=> PLANET-1865 In split two columns where issue name has special chars

classes/controller/blocks/class-carousel-controller.php, includes/blocks/carousel.twig
Change carousel block to use image/attachment caption and credit fields. 
Remove image caption from top right corner in carousel block.
Do not show blue overlay if neither of image caption and credits are defined.
[Issue 1771](https://jira.greenpeace.org/browse/PLANET-1771)
=> PLANET-1771 Carousel block image/attachment caption and credits

classes/controller/blocks/class-carousel-controller.php, includes/blocks/carousel.twig
Generate a unique id for carousel block to allow multiple carousels to be used in the same post/page.
Also minor changes based on codesniffer warnings.
[Issue 1927](https://jira.greenpeace.org/browse/PLANET-1927)
=> PLANET-1927 Generate unique id for carousel block

classes/controller/blocks/class-splittwocolumns-controller.php
This negates the need for PLANET-1889
The need to assign pages to a category was because we needed a way to select a category for the split-two-column, and show the associated page.
But in reality we don't need to select a category. We need to select a page.
So, by changing the logic of the block, and selecting only pages which are children of the "Explore" page, we achieve the same result, without needing any more the requirement that "A page and a category must have the same name"
=> PLANET-1942 instead of category select a subpage of explore

classes/controller/blocks/class-carouselheader-controller.php, includes/blocks/carousel_header.twig
Calculate img srcset for image in carousel header based on retina-large size
[Issue 1926](https://jira.greenpeace.org/browse/PLANET-1926)
This is related to https://github.com/greenpeace/planet4-master-theme/pull/355
=> PLANET-1926 Carousel header responsive images

classes/controller/blocks/class-articles-controller.php, includes/blocks/articles.twig
Use custom image size for articles block images.
Use different markup for images in articles block depending on their aspect ratio.
This PR is related to [this](https://github.com/greenpeace/planet4-master-theme/pull/361)
You can check how it looks [here](https://jira.greenpeace.org/browse/PLANET-1924?focusedCommentId=62674&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-62674)
[Issue 1814](https://jira.greenpeace.org/browse/PLANET-1814)
[Issue 1924](https://jira.greenpeace.org/browse/PLANET-1924)
=> PLANET-1924 Articles block portrait images

includes/blocks/static_four_column.twig
The change here is that I wrapped the `four-column-wrap` column under an `if` statement to make sure we actually have content to display. 
As an example see the [About Us](https://dev.p4.greenpeace.org/international/about/) page, where we have content for 3 columns but we render 4, preventing the block from expanding to full width.
=> PLANET-1868 - Adjust four column block to make it responsive

classes/controller/blocks/class-happypoint-controller.php, includes/blocks/happy_point.twig
Since we use an img for happy-point, instead of background, I added a default fallback for cases where a background image has not been set.
=> Add default happy-point picture

classes/controller/blocks/class-contentfourcolumn-controller.php, includes/blocks/content_four_column.twig
Add Selection of number of Rows for the Content Four Column Block. Editors can select 1, 2 or all rows of Posts to appear.
[Issue 1916](https://jira.greenpeace.org/browse/PLANET-1916)
Includes also [Issue 1974](https://jira.greenpeace.org/browse/PLANET-1974)
=> PLANET-1916 contentfourcolumn-update

classes/controller/blocks/class-splittwocolumns-controller.php
[Issue 2090](https://jira.greenpeace.org/browse/PLANET-2090)
=> PLANET-2090 Allow html special chars for split two column tag name.

includes/blocks/tasks.twig
This a minor markup change needed by greenpeace/planet4-master-theme#499
=> PLANET-2261 - Use two circles for Take Action numbers

classes/class-loader.php, classes/view/class-view.php
Allow registration of a shortcake block from outside of this plugin. The external blocks are registered after all plugins are loaded. Renamed View argument to make more sense.
related to this [PR](https://github.com/greenpeace/planet4-plugin-engagingnetworks/pull/21)
=> PLANET-2149 add enform block

classes/controller/blocks/class-covers-controllers.php
Use 'large' size background images for take action covers in Covers block, instead of using unecessarily the full sizes image.
=> PLANET-2426 covers smaller images

assets/scss/blocks/_happy_point.scss
It seems that our sass rendered (pscss) has a known bug with nested `@supports` attribute. This is a fixed to nest it properly.
=> Fix @supports nesting

classes/controller/blocks/class-articles-controller.php
Select posts based on page's tags.
When no page types, tags or specific posts are selected it will select posts based on the page's tags that the shortcode is embedded into.
Fixes explore pages.
https://jira.greenpeace.org/browse/PLANET-2412?focusedCommentId=66757&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-66757
=> PLANET-2412 Add sixth scenario in articles block.

classes/controller/blocks/class-articles-controller.php
In "Read more" link of article block on tag page, replace duble slash [//] with one slash[/] for multilingual site.
eg. https://master.k8s.p4.greenpeace.org/luxembourg/de//?s=&orderby=post_date&f[ctype][Post]=3&f[tag][Ozeane]=56
[Related PR](https://github.com/greenpeace/planet4-master-theme/pull/589)
=> PLANET-2758 Fix tag page article block readmore button issue for multilingual site

classes/controller/blocks/class-controller.php
Editor disappeared from Post Edit page. Looks like the `wp_filesystem` call is causing the problem.
I just restored the original version, feel free to change it if you find a better method.
Screenshot:
=> PLANET - no issue: Fix TinyMCE disappearing from Post edit

classes/controller/blocks/class-carousel-controller.php, tests/unit/test-carousel.php
I moved the `$images` initialization outside the loop, which seems more logical, and type casted to array to stop `count()` from complaining.
This fixes the error we had (`php count(): Parameter must be an array or an object that implements Countable`).
We still have an [error](https://circleci.com/gh/greenpeace/planet4-plugin-blocks/702) the Carousel unit test, but we have it on all php environments, so not sure if it's relevant to this.
```
P4_CarouselTest::test_attachments_count
->Did not find as many Attachments as expected.
/home/circleci/project/tests/unit/test-carousel.php:53
```
Thanks @angtheod for help! :beers:
=> PLANET-2739 - Fix Carousel Header Controller

classes/controller/blocks/class-controller.php
Add an ignore as the nonce verification is not really needed. 
There are user & capability checks before and it's only a read request.
=> PLANET-2874 Ignore sniff error for nonce verification

gulpfile.js
This will allow us to run gulp for both `master-theme` and and `plugin-blocks`.
=> PLANET-2892 - Add port to livereload

classes/controller/blocks/class-covers-controller.php, classes/controller/blocks/class-newcovers-controller.php, planet4-blocks.php
Some texts had a hardcoded ellipsis. 
@kirdia @koyan  ⚠️ I guess this will need some updates to the PO files. 
Ref: https://jira.greenpeace.org/browse/PLANET-2929
=> PLANET-2929: Covers block: Load More button has an ellipsis

classes/controller/blocks/class-covers-controller.php, classes/controller/blocks/class-newcovers-controller.php
[JIRA issue #2910](https://jira.greenpeace.org/browse/PLANET-2910)
The updated sort order behaviour [reference.](https://planet4.greenpeace.org/handbook/block-covers/#behaviour-of-covers)
Note : The changes are made for both blocks (Old [Take action Covers] covers block and new Covers block )
=> PLANET-2910 - Covers block - Updated the default sort order behavior

package.json, yarn.lock
Currently on `develop` the yarn install fails because flatmap-stream [has been removed from npm](https://www.npmjs.com/package/flatmap-stream).
gulp-livereload 4.0.1 [pins event-stream to 3.3.4](https://github.com/vohof/gulp-livereload/pull/140) which predates the flatmap-stream security vulnerability.
=> Upgrade gulp-livereload to avoid flatmap issue

planet4-blocks.php
Relevant Jira issue [PLANET-3034](https://jira.greenpeace.org/browse/PLANET-3034)
Reorder plugin blocks report to be alphabetical
And fix a couple of phpcs errors
=> PLANET-3034 - Reorder plugin blocks report to be alphabetical

classes/controller/blocks/class-carousel-controller.php, classes/controller/blocks/class-contentthreecolumn-controller.php, classes/controller/blocks/class-staticfourcolumn-controller.php, classes/controller/blocks/class-tasks-controller.php, classes/controller/blocks/class-twocolumn-controller.php
[Related Jira Issue](https://jira.greenpeace.org/browse/PLANET-3227)
Making the 5 blocks that we have replaced not available in the interface, while leaving them working (for any pages that still have them).
This is temporary, until the NROs replace their existing blocks with the new ones, in which time we will completely remove these 5 from our codebase
=> PLANET-3227 remove old blocks

planet4-blocks.php
Functionality described at: [PLANET-3231](https://jira.greenpeace.org/browse/PLANET-3231)
It can be called at: https://mywebsite/wp-json/plugin_blocks/v1/plugin_blocks_report/
It results in an JSON like the following:
=> PLANET 3231 - Add an API call that exports the plugin blocks usage

assets/scss/components/_articles.scss
This reverts a change made to the articles block to add some padding to the top which caused the present bug. The padding should be added only for the explore page, not for *every* articles block. 
So this fixes the "Double vertical spacing" issue, but "unfixes" the previous one (3158, add spacing in the explore page), which should probably be reopened.
Ref: https://jira.greenpeace.org/browse/PLANET-3218
=> PLANET-3218: Double vertical spacing

classes/view/class-view.php
Clear Timber's cache as well to avoid cache issue with rendering block changes.
Related with [PR](https://github.com/greenpeace/planet4-master-theme/pull/723/files)
=> PLANET-2981 cache blocks issue

.circleci/config.yml
Run test codeception tests in ci as in master-theme.
Ci job
https://circleci.com/gh/greenpeace/planet4-builder/502
Uses that builder branch. Needs that PR merged first.
https://github.com/greenpeace/planet4-builder/pull/25
=> PLANET-3240 Add test codeception ci job

planet4-blocks.php
[Jira issue 3372](https://jira.greenpeace.org/browse/PLANET-3346)
This adds two rows to the plugins usage report about which style of the carousel Header block is used
In the admin pages of wordpress:
And in the json for the automatic report
Additionally it fixes a bug that existed that was making the "Carousel" to also report all  "Carousel_header" blocks.
=> PLANET-3372 Added report for different carousel header styles

includes/blocks/carousel_header_full-width-classic.twig
Reported via Rocket Chat, no JIRA issue.
=> Carousel Header: Truncate 32 chars instead of 30 in twig (no JIRA issue)

.circleci/config.yml
As planet4-docker now builds with PHP7.3, this adds PHP v7.3 test environment and removes 7.1 and 7.2
Will be ready to merge when:
1. redis connection issue in codeception tests is identified
2. https://github.com/greenpeace/planet4-circleci-unit-tests/pull/2 is merged
=> Testing in PHP 7.3

classes/class-loader.php, classes/controller/menu/class-blocks-usage-controller.php, classes/controller/menu/class-settings-controller.php, includes/settings.twig, planet4-blocks.php, vendor/composer/ClassLoader.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php
Add Menu Item for Blocks and a submenu item. The Blocks Usage logic was moved to the submenu item and in the main menu item we added a button and an input for Editors to use for replacing block shortcodes with new ones.
*`class-blocks-usage-controller.php` has the code that was in plugin-blocks.php (related to block usage report functionality)... so no real changes on this one, only restructured so that it becomes a submenu item.
=> PLANET-3380 admin convert blocks

classes/controller/blocks/class-carousel-controller.php, classes/controller/blocks/class-gallery-controller.php
Ref: https://jira.greenpeace.org/browse/PLANET-3347
A bit of context: there was a function for generating a hash for the carousel/gallery (depending on the block version), which was based on title + image dimensions. As the title may be absent and the image dimensions may be the same for two galleries (specially since images are normalized and cropped), looks like there is no need to base the hash on those two parameters. I replaced the function with `uniqid`. These hashes are only needed for the DOM.
=> PLANET-3347: #375896 having multiple carousels in a post some may seem unresponsive to manual scroll

classes/controller/blocks/class-covers-controller.php, classes/controller/blocks/class-newcovers-controller.php
Fixes https://github.com/greenpeace/planet4-plugin-blocks/issues/544
Where in php7.2 the get_the_excerpt is called from outside the loop, it throws the error reported in the [Jira ticket](https://jira.greenpeace.org/browse/PLANET-3506). 
Since we have already loaded the whole post (which is saved in the $action as a wp object), and it already has the parameter post_excerpt in it, we don't need to call a separate function to retrieve it.
=> PLANET-3506 The wp object $action that we use already has the excerpt

includes/blocks/split_two_columns.twig
This reverts commit 384514aeca2ed06fb3aae9c517ae90de91baa203.
Not sure why this change happened initially. @pablocubico maybe you have some insight?
=> PLANET-3508 - Remove button class from Split Two Column CTA

.gitignore, composer.json
Now that no longer have vendor files in the repo, it's safe to add the same dev dependencies we have on master-theme.
Updated the gitignore to ignore all generated vendor files.
=> Add local testing dependencies

classes/controller/blocks/class-counter-controller.php, tests/unit/test-counter.php
[Jira issue: PLANET-3565](https://jira.greenpeace.org/browse/PLANET-3565)
Added functionality that allows editors to define an API URL from the global counter application. 
If such a url is added, AND it returns a valid Json, with a field named "unique_count" AND the value is an integer, then the manual "completed" field is overwritten by the one returned by the API. 
To test it: Create a new counter block, and add the url that is defined in the description of the Jira ticket.
=> Planet-3565 Counter block - Use API if API is given

classes/controller/blocks/class-counter-controller.php
As per feedback on https://github.com/greenpeace/planet4-plugin-blocks/pull/562
=> PLANET-3565 use wp_safe_remote_get instead of wp_remote_get

classes/controller/menu/class-blocks-usage-controller.php, planet4-blocks.php
[JIRA ticket](https://jira.greenpeace.org/browse/PLANET-3566)
Add to the plugins report with a breakdown which tags are use redirection and which do not. 
Add it to both the report in the backend, and the json exported. 
While this funcionality (tags with redirection) is not part of the plugins block but of the master theme, we add it to the plugins report, because it is already exporting data to the external place we want to report to.
Note: After all NROs/sites have switched all their tag pages to redirect instead of auto generation, we will retire the functionality for redirection, and we will then retire this part of the report as well.
You can demo the functionality 
a) By seeing the report in the Backend -> Blocks -> usage menu
b) by going to the url …
=> PLANET-3566 Add to the plugins report  which tags are use redirection

classes/controller/menu/class-blocks-usage-controller.php, planet4-blocks.php
Related previous PR: https://github.com/greenpeace/planet4-plugin-blocks/pull/568
The functionality does not change, but gets fixed. 
Make a double (Union) query to include also the tags that do not have a `redirect_page` meta_key
Before, it was working only for tags that had been saved once after the meta_key has been introduced
=> PLANET-3566 Fix report for tags that do not use redirection

classes/controller/blocks/class-articles-controller.php
Check that posts and post_types do not have have a value to ensure that articles block works for tag pages even if a tag redirect page is set.
Ref: https://jira.greenpeace.org/browse/PLANET-3654
=> PLANET-3654 Add extra check for articles block rendered inside a tag page

includes/blocks/articles.twig, includes/blocks/campaign_thumbnail.twig, includes/blocks/columns.twig, includes/blocks/columns_tasks.twig, includes/blocks/content_four_column.twig, includes/blocks/content_three_column.twig, includes/blocks/cookies.twig, includes/blocks/counter.twig, includes/blocks/covers.twig, includes/blocks/gallery.twig, includes/blocks/media_video.twig, includes/blocks/social_media.twig, includes/blocks/subheader.twig, includes/blocks/tasks.twig, includes/blocks/timeline.twig
Ref: https://jira.greenpeace.org/browse/PLANET-3841
Note: the ticket is about the columns block, but this was happening in all blocks since the description can contain `<p>` paragraphs, but `<p>` elements apparently should not be nested according to: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p
This also needs a minor change in the styleguide: https://github.com/greenpeace/planet4-styleguide/pull/9
=> PLANET-3841: Columns block: font (and size) changing when adding paragraph in block descriptions

classes/controller/blocks/class-carouselheader-controller.php, includes/blocks/carousel_header_full-width-classic.twig, includes/blocks/carousel_header_zoom-and-slide-to-gray.twig
After the change introduced at 18b53a6e15af3da98b2df5e81ec36882e29bfea3 there was no default heading and that breaks existing instances of Carousel Header.
=> Carousel Header: Use h1 as default option

classes/controller/blocks/class-columns-controller.php
Use articles-medium-large image size in columns block for more than 1 column set.
---
Wide screen medium image size thumbnail
---
Wide screen articles-medium-large image size thumbnail
---
Small screen medium image size thumbnail
---
Small screen articles-medium-large image size thumbnail
=> PLANET-3892 Use a larger image size when more than one column is set

.circleci/config.yml, gulpfile.js
Double asterisk patterns need double quotes to work properly.
=> Fix stylelint and eslint paths

classes/command/class-shortcodereplacer.php
Add suppress_filters arg in shortcode replacer to retrieve posts from all languages when WPML is detected.
=> PLANET-4000 Enhance shortcode replacer to query for posts from all languages
