greenpeace/planet4-plugin-blocks

classes/controller/blocks/class-p4bks-blocks-covers-controllers.php, includes/blocks/covers.twig
Added optional Tag selection, so that Editors can display only Action…
=> Feature/1323 Block: Covers

classes/controller/blocks/class-p4bks-blocks-carouselsplit-controller.php, includes/blocks/carousel_split.twig
Tested with jquery 3.2.1 and latest stylesheet. Works as in the presentation layer
=> Added latest markup, copyright/credit header

classes/controller/blocks/class-p4bks-blocks-controller.php
Reopening from https://github.com/greenpeace/planet4-plugin-blocks/pull/56 to finish off some minor code review fixes
=> 1413 shortcode previews - minor fixes from review2

classes/controller/blocks/class-p4bks-blocks-campaignthumbnail-controller.php
=> PLANET-1320 campaign thumbnail image blurr issue

classes/controller/blocks/class-covers-controllers.php, includes/blocks/covers.twig
Added latest markup for covers block for presentation layer.
=> Reintroduced code for multiple tags selection in covers block.

includes/blocks/split_two_columns.twig
Latest markup from explore page in presentation layer.
=> Added new markup for split two columns block.

includes/blocks/campaign_thumbnail.twig, includes/blocks/content_three_column.twig, includes/blocks/media_block.twig
We are converting img tags in twig templates with img tags with srcet attribute, that will enable us serving different images based on the device.
=> Add img tag with srcset in twig templates.

includes/blocks/content_three_column.twig
Based on https://github.com/greenpeace/planet4-presentation-layer/pull/113
=> Updated markup of content three column block

includes/blocks/static_four_column.twig
Based on https://github.com/greenpeace/planet4-presentation-layer/pull/123
=> Latest markup for static four column

includes/blocks/covers.twig
Based on https://github.com/greenpeace/planet4-presentation-layer/pull/116
=> Updated markup for covers

includes/blocks/articles.twig, includes/blocks/campaign_thumbnail.twig, includes/blocks/content_four_column.twig, includes/blocks/media_video.twig
as per https://github.com/greenpeace/planet4-presentation-layer/pull/91
=> Update markup for title size and class

classes/controller/blocks/class-campaignthumbnail-controller.php, classes/controller/blocks/class-contentfourcolumn-controller.php, includes/blocks/campaign_thumbnail.twig, includes/blocks/content_four_column.twig
Remove timber resizing from content four column. Use medium image size.
=> Remove timber resizing from blocks.

classes/controller/blocks/class-articles-controller.php, includes/blocks/articles.twig
Line 74 of the feedback document
=> Show post type instead of categories in articles listing

classes/controller/blocks/class-carouselheader-controller.php, classes/controller/blocks/class-mediablock-controller.php, classes/controller/blocks/class-staticfourcolumn-controller.php, classes/controller/blocks/class-tasks-controller.php, includes/blocks/articles.twig, includes/blocks/take_action_boxout.twig, includes/settings.twig
=> Translation of localised messages on planet4-blocks

classes/controller/blocks/class-carouselheader-controller.php, classes/controller/blocks/class-contentthreecolumn-controller.php, classes/controller/blocks/class-staticfourcolumn-controller.php, classes/controller/blocks/class-tasks-controller.php
=> Escape all outputs in plugin blocks

includes/blocks/content_four_column.twig, includes/blocks/covers.twig
Changed content four column and covers block to work with changed load more button functionality.
=> Change css class names for load more button functionality.

classes/controller/blocks/class-articles-controller.php
Add default link to search results for read all news button in articles block.
=> Add default link for read all news button in articles block.

includes/blocks/carousel_header.twig
Latest markup from presentation layer.
=> Updated markup for carousel header block.

includes/blocks/content_four_column.twig
Add empty columns in last row of content four column block, in order to preserve presentation.
=> Add empty columns in last row of content four column block.

classes/controller/blocks/class-contentfourcolumn-controller.php, classes/controller/blocks/class-splittwocolumns-controller.php
Change Split Two Columns right side button text. Prevent warning for array_filter 1st param.
=> Presentation fixes - Spreadsheet issue 144

includes/blocks/tasks.twig
Feedback issue no #148 - Unable to add paragraph breaks to Description field - appearing as <br>
=> Task block - line break issue

classes/controller/blocks/class-articles-controller.php
to get rid of notice error in case there are no categories
Spreadsheet issue 154
=> PreDefined variable

includes/blocks/tasks.twig
Feedback issue no 148 - Tasks block description br tag issue in loop
=> Tasks block description br tag issue in loop

classes/controller/blocks/class-articles-controller.php, includes/blocks/articles.twig
Update Block Articles to make the Read All The News button text customizable by web editors. Applied few coding standards while at it.
=> Block articles update - Spreadsheet issue 108

includes/blocks/covers.twig, includes/blocks/take_action_boxout.twig
This is a design fix to improve readability of tags and titles on action cards
=> Add background gradient to cover cards

classes/controller/blocks/class-happypoint-controller.php
PLANET-1585 label changed for block
=> happy point label change for opacity

includes/blocks/two_columns.twig
according to https://github.com/greenpeace/planet4-presentation-layer/pull/179/files
Identation will change from spaces to tabs in an other PR, so that it is clear what these changes are
=> Changed markup for new design

classes/controller/blocks/class-splittwocolumns-controller.php, includes/blocks/split_two_columns.twig
=> use img tag instead of css background image

classes/controller/blocks/class-articles-controller.php
Fetch only published posts for articles block.
Use p4_author_override meta if it is available as the author name.
Issues [1643](https://jira.greenpeace.org/browse/PLANET-1643), [1644](https://jira.greenpeace.org/browse/PLANET-1644)
=> Use published posts for articles block. Use p4_author_override field.

includes/blocks/articles.twig
Based on greenpeace/planet4-presentation-layer#198
=> Minor markup change on articles-listing

includes/blocks/covers.twig
This is a change overwritten by mistake since I had forgotten to add it to the presentation layer.
Relevant PR: greenpeace/planet4-presentation-layer#199
=> Add gradients to covers blocks for legibility

includes/blocks/covers.twig
I accidentally opened the PR on master. I guess we need it this on develop too.
=> Fix covers grid

includes/blocks/covers.twig
Reverts greenpeace/planet4-plugin-blocks#188
=> Revert "Fix covers grid"

includes/blocks/take_action_boxout.twig
Escape page title and excerpt in take action boxout block.
=> Add escaping in take action boxout block.

includes/blocks/articles.twig, includes/blocks/content_four_column.twig, includes/blocks/covers.twig
* Change button size on Articles
* Change size and margin on four column button
These are the markup changes from greenpeace/planet4-presentation-layer#206
=> Minor design changes

includes/blocks/covers.twig
Add cover-card-column class in each cover column div.
Related to this [comment](https://jira.greenpeace.org/browse/PLANET-1633?focusedCommentId=60913&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-60913)
=> Slight change in covers markup

includes/blocks/carousel_header.twig
Based on changes from greenpeace/planet4-presentation-layer#217
=> Add a clear div to carousel-header

includes/blocks/carousel_header.twig, includes/blocks/happy_point.twig
Minor markup change per greenpeace/planet4-master-theme#223
=> Add a new class to wide blocks

includes/blocks/covers.twig, includes/blocks/take_action_boxout.twig
Markup changes per greenpeace/planet4-master-theme#238
=> Adjust cover cards for legibility

classes/controller/blocks/class-contentfourcolumn-controller.php, includes/blocks/content_four_column.twig
in the block content-four-column
=> PLANET-1738 Add srcset to publication cards

includes/blocks/media_video.twig
Removed container class from media_video.twig
=> Bug fix for PLANET-1596

classes/controller/blocks/class-carouselheader-controller.php
Reverts greenpeace/planet4-plugin-blocks#216
=> Revert "switched to large from specific size"

classes/controller/blocks/class-carousel-controller.php, classes/controller/blocks/class-carouselheader-controller.php
Reverts greenpeace/planet4-plugin-blocks#214
=> Revert "PLANET-1820 Switch image sizes from full to large"

classes/controller/blocks/class-covers-controllers.php, includes/blocks/covers.twig
Add option to show 3 covers in covers block
[Issue 1633](https://jira.greenpeace.org/browse/PLANET-1633?focusedCommentId=60846&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-60846)
=> [PLANET-1633] Add 3 covers option in covers block

includes/blocks/articles.twig, includes/blocks/carousel.twig, includes/blocks/content_four_column.twig, includes/blocks/covers.twig, includes/blocks/tasks.twig
Along with some markup changes to replace deprecated classes
=> Upgrade to bootstrap4

classes/controller/blocks/class-splittwocolumns-controller.php
pages with the same title. Also getting rid of extra function call (since we already have the data we want right there).
Overiding the merge freeze, as this blocks the greek office from adding the correct content
=> PLANET-1862 . Decoding title of category before using it to pick up

classes/controller/blocks/class-carouselheader-controller.php
[Issue 1826](https://jira.greenpeace.org/browse/PLANET-1826)
=> [PLANET-1826] Subheader attribute in carousel header

classes/controller/blocks/class-articles-controller.php, classes/controller/blocks/class-campaignthumbnail-controller.php, classes/controller/blocks/class-carousel-controller.php, classes/controller/blocks/class-carouselheader-controller.php, classes/controller/blocks/class-carouselsplit-controller.php, classes/controller/blocks/class-contentfourcolumn-controller.php, classes/controller/blocks/class-contentthreecolumn-controller.php, classes/controller/blocks/class-covers-controllers.php, classes/controller/blocks/class-happypoint-controller.php, classes/controller/blocks/class-mediablock-controller.php, classes/controller/blocks/class-mediavideo-controller.php, classes/controller/blocks/class-splittwocolumns-controller.php, classes/controller/blocks/class-staticfourcolumn-controller.php, classes/controller/blocks/class-subheader-controller.php, classes/controller/blocks/class-takeactionboxout-controllers.php, classes/controller/blocks/class-tasks-controller.php, classes/controller/blocks/class-twocolumn-controller.php, planet4-blocks.php
[JIRA #1821](https://jira.greenpeace.org/browse/PLANET-1821)
[Related PR](https://github.com/greenpeace/planet4-master-theme/pull/291)
=> PLANET-1821 Added ALLOWED_PAGETYPE contant in block plugin

classes/controller/blocks/class-articles-controller.php
[JIRA #1825](https://jira.greenpeace.org/browse/PLANET-1825)
[Related PR](https://github.com/greenpeace/planet4-master-theme/pull/297)
=> PLANET-1825 Added default text settings for Article block

classes/controller/blocks/class-takeactionboxout-controllers.php, includes/blocks/take_action_boxout.twig
Consider all of the campaign tags that are related to the Take Action Boxout block. Renamed twig variable to match better the context.
=> PLANET-1809 fix boxout tags

classes/controller/blocks/class-covers-controllers.php
[Related PR](https://github.com/greenpeace/planet4-master-theme/pull/309)
=> PLANET-1816 Apply default p4 take action button text setting

includes/blocks/covers.twig
Remove unused class.
Related to https://github.com/greenpeace/planet4-master-theme/pull/328
=> PLANET-1875 fix covers load more

includes/blocks/articles.twig, includes/blocks/content_four_column.twig
* Adjust Articles block
* Adjust four column block
=> PLANET-1883 Make links behaviour consistent

includes/blocks/carousel.twig
Small changes to carousel block caption section based on [comments on Issue 1771](https://jira.greenpeace.org/browse/PLANET-1771?focusedCommentId=62324&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-62324)
=> PLANET-1771 Small changes to carousel block caption section.

classes/controller/blocks/class-covers-controllers.php
Edit covers block drop down options.
=> PLANET-1933 covers update descriptions

classes/controller/blocks/class-articles-controller.php
Code blatantly copied (and variable names adjusted) from content four column block
=> PLANET-2013 Allow editors to filter articles based on p4_page_type.

classes/controller/blocks/class-articles-controller.php, includes/blocks/articles.twig
so that pagetypes can be set as the only criteria
Also, made pagetype appear even if there is no tag
=> PLANET-2013 Added parameter for ignoring categories filtering

includes/blocks/covers.twig
Fix incorrect dropdown values.
=> PLANET-1989 fix covers rows selection

includes/blocks/happy_point.twig
A small markup adjustment for greenpeace/planet4-master-theme#380 to work.
=> PLANET-1996 - Load happy point iframe when user scrolls

classes/controller/blocks/class-happypoint-controller.php, includes/blocks/happy_point.twig
Populate img srcset & sizes attributes for happy point block image.
[Issue 1936](https://jira.greenpeace.org/browse/PLANET-1936)
=> PLANET-1936 Add img srcset to happy point block image.

includes/blocks/two_columns.twig
Figure out a way using flexbox `order-*` to deduplicate the markup code.
=> PLANET-1997 - Simplify Two Column block grid

includes/blocks/submenu.twig
A simple markup change needed for greenpeace/planet4-master-theme#404
=> PLANET-2075 - Initial frontend implementation of Submenu

classes/controller/blocks/class-takeactionboxout-controllers.php, includes/blocks/take_action_boxout.twig
[Issue 2095](https://jira.greenpeace.org/browse/PLANET-2095)
=> PLANET-2095 Use planet4 settings for take action boxout button text.

includes/blocks/split_two_columns.twig
This reverts commit c473f3f4811dde9098873fde295acd5ab1e4f136.
=> Revert "PLANET-2103 - Add vertical spacing to articles block"

classes/controller/blocks/class-happypoint-controller.php
[JIRA 2130](https://jira.greenpeace.org/browse/PLANET-2130)
[Related PR](https://github.com/greenpeace/planet4-master-theme/pull/427)
=> PLANET-2130 Display default happy point bg image as per p4 settings

admin/js/submenu.js, includes/blocks/submenu.twig
[Issue 2178](https://jira.greenpeace.org/browse/PLANET-2178)
=> PLANET-2178 Add scroll animation for submenu block links

classes/controller/blocks/class-articles-controller.php
Use posts based on page's tags in articles block.
Minor code inspection error fixes.
[Issue 2187](https://jira.greenpeace.org/browse/PLANET-2187)
=> PLANET-2187 Use posts based on page's tags in articles block

classes/controller/blocks/class-happypoint-controller.php, includes/blocks/happy_point.twig
[Issue 2224](https://jira.greenpeace.org/browse/PLANET-2224)
=> PLANET-2224 Add url field to override iframe url in happy point

includes/blocks/static_four_column.twig
[Related PR](https://github.com/greenpeace/planet4-master-theme/pull/506)
=> PLANET-2083 Change static four column header title from h2 to h3

includes/blocks/covers.twig
Along with greenpeace/planet4-master-theme#515 this will fix the bug
=> PLANET-2399 - Covers: Limit the amount of words

classes/controller/blocks/class-submenu-controller.php
This is an extra for planet-2386 to fix submenu block anchor links.
=> PLANET-2386 Translate/remove utf8 characters for submenu block links

assets/scss/blocks/_tasks.scss
A complementary PR. Accidentally I only fixed the font on hover/active state.
=> PLANET-2527 - Fix font for all states

includes/blocks/articles.twig
This should be merged along with greenpeace/planet4-master-theme#543
=> PLANET-2510 - Articles block: Add description field

assets/scss/blocks/_tasks.scss
I also moved some code to have proper nesting for this element.
=> PLANET-2527 - Tasks block: Use Roboto on mobile headers

.circleci/config.yml, .phpcs.xml.dist, bin/install-wp-tests.sh, phpunit.xml.dist, tests/bootstrap.php, tests/test-sample.php
Issue https://github.com/greenpeace/planet4-plugin-blocks/issues/335
=> Updated circle ci config file to 2.0 by updating wp-cli to 2.0.0

includes/blocks/tasks.twig
=> PLANET-2590 Allow html in description for tasks block-mobile view

classes/controller/blocks/class-contentfourcolumn-controller.php
Inside the ContentFourColumn block show all related results (instead of just the first 10).
=> PLANET-2491 cfc show all related posts

assets/scss/blocks/_submenu.scss
Adding an additional explicit selector for the default page template
=> PLANET-2554 - Fix back-to-top icon for default page template

admin/js/blocks-ui.js
Fix bug introduced from url encoding read more link in articles block.
=> PLANET-2625 Fix urlencoding in articles block backend

includes/blocks/campaign_thumbnail.twig, includes/blocks/content_four_column.twig
Render html for campaign thumbnail and content four column description fields
=> PLANET-2751 New covers support html in description fields

includes/blocks/campaign_thumbnail.twig
A small fix to make Campaigns button consistent
=> PLANET-2752 - Campaigns: Fix button spacing

classes/controller/blocks/class-articles-controller.php, includes/blocks/articles.twig
As I changed Page Type links in the master theme, I'm doing the same here for consistency.
Ref. issue: https://jira.greenpeace.org/browse/PLANET-2614
More details on: https://github.com/greenpeace/planet4-master-theme/pull/587
=> Use Page Type slug in articles block.

classes/controller/blocks/class-articles-controller.php
Note: Here we are fetching all posts from DB, If there are thousands of posts then it will impact on page load performance.
=> PLANET-2932 Load all post on articles block load more

classes/controller/blocks/class-articles-controller.php
Set a high enough max number of articles to load within the Articles block.
=> PLANET-2932 articles results number

includes/teasers/tease-articles.twig
Related to https://github.com/greenpeace/planet4-master-theme/pull/658
=> PLANET-3004 Fix truncate post excerpt for character based languages

includes/blocks/carousel.twig
Adds an extra div to the carousel view, which is needed for the new campaign theme styles
=> Adapt carousel block for new theme styles 

.circleci/config.yml, composer.json
Use repo's dev dependencies versions (phpcs, phpunit), instead of configuring them in ci.
=> Update circleci config

includes/blocks/gallery.twig
Ref: https://jira.greenpeace.org/browse/PLANET-3178
Note: 
The file indentation was all wrong, probably due to automatic reformatting, check it without whitespace diffs to see what actually changed: https://github.com/greenpeace/planet4-plugin-blocks/pull/457/files?utf8=%E2%9C%93&diff=unified&w=1
=> PLANET-3178: #369155: Gallery block: Description field not displaying

includes/blocks/columns.twig, includes/blocks/columns_tasks.twig
The description markup was missing from some Column variations.
Ref: https://jira.greenpeace.org/browse/PLANET-3189
=> PLANET-3189 - Columns: Show description on all variations

includes/blocks/carousel_header.twig
=> PLANET-3179: Reverse condition

.circleci/config.yml
Adapt changes to docker-compose makefile done here greenpeace/planet4-docker-compose@ee9ba1c
=> Adapt docker compose make targets change

admin/css/admin_blocks.css, admin/js/blocks-ui.js
Ref: https://jira.greenpeace.org/browse/PLANET-3276
=> PLANET-3276: New Carousel header - display character number limitation on Wordpress.

classes/view/class-view.php
Revert changes that did not help.
Related to this [PR](https://github.com/greenpeace/planet4-master-theme/pull/736)
=> PLANET-3268 object cache issue

.circleci/config.yml
Change unit test ci jobs to use gcr.io/planet-4-151612/p4-unit-tests image
=> PLANET-3305 Use p4-unit-tests image for ci unit test jobs

classes/controller/blocks/class-articles-controller.php, classes/controller/blocks/class-contentfourcolumn-controller.php, includes/blocks/content_four_column.twig, includes/teasers/tease-articles.twig
Ref: https://jira.greenpeace.org/browse/PLANET-3310
GH Issue: https://github.com/greenpeace/planet4-plugin-blocks/issues/509
=> PLANET-3310: Fix E_USER_WARNING errors by removing deprecated post.permalink references

classes/command/class-shortcodereplacer.php, planet4-blocks.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php
(FYI, the bulk of this work was done by @rasmuswinter before I tided up some loose ends and added it to this blocks plugin)
https://jira.greenpeace.org/browse/PLANET-3264
* `vendor/bin/wp replace-shortcodes` - to update all posts
* `vendor/bin/wp replace-shortcodes <post_id>` - to update a specific post
The command will replace the following blocks with the Gallery block:
* Three columns
* Carousel
And it will replace the following blocks with the Columns block:
* Static four column
* Two columns
* Take action tasks
All the conversion rules are detailed in the comments of the relevant methods of the `ShortcodeReplacer` class, along with examples of the old blocks and what they will be converted into.
We haven't tested on much actual data so would be grateful for some help with this (by …
=> PLANET-3264: Add command to replace old shortcodes with new equivalents

classes/controller/blocks/class-gallery-controller.php, includes/blocks/gallery.twig
Ref: https://jira.greenpeace.org/browse/PLANET-3346
=> PLANET-3346: Gallery Block, Three columns style: Uses full images instead of thumbnails

classes/controller/blocks/class-timeline-controller.php
Fix for https://jira.greenpeace.org/browse/PLANET-3382
=> PLANET-3382 - fix timeline 'start at end' option

includes/blocks/split_two_columns.twig
Ref: https://jira.greenpeace.org/browse/PLANET-3398
This has a matching PR in the master theme: https://github.com/greenpeace/planet4-master-theme/pull/753
=> PLANET-3398: CPP - Fix Secondary button colors across all blocks

planet4-blocks.php
=> PLANET-3380 admin convert blocks 2

classes/class-loader.php, classes/command/class-controller.php, planet4-blocks.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php
Create class for adding p4-blocks sub-commands.
Moved commands code from main plugin file into this class.
Now we can create sub-commands by adding a method in this class.
=> PLANET-3431 restructure commands code

assets/scss/components/_articles.scss, includes/blocks/articles.twig, includes/blocks/carousel_header_full-width-classic.twig, includes/blocks/carousel_header_zoom-and-slide-to-gray.twig, includes/blocks/columns.twig, includes/blocks/columns_tasks.twig, includes/blocks/cookies.twig, includes/blocks/covers.twig, includes/blocks/gallery.twig, includes/blocks/media_video.twig, includes/blocks/social_media.twig, includes/blocks/subheader.twig
Ref: https://jira.greenpeace.org/browse/PLANET-3526
I opened a PR to fix the tests that are failing because of these changes: greenpeace/planet4-base-fork#31
=> PLANET-3526 - Make blocks headings consistent

includes/blocks/split_two_columns.twig
- Initial PR erroneously applied issue image focus to campaign image
- Apply campaign image focus to campaign image
=> PLANET-3530-fix Fixed campaign referencing same focus as issue.

classes/controller/blocks/class-media-controller.php, includes/blocks/media_video.twig
Ref: https://jira.greenpeace.org/browse/PLANET-3558
=> PLANET-3558 - Add description to Media block

classes/controller/blocks/class-timeline-controller.php, includes/blocks/timeline.twig
Ref: https://jira.greenpeace.org/browse/PLANET-3559
=> PLANET-3559: Add Title and Description to Timeline block

classes/class-loader.php
Refactors conditional so it is able to return something else than 'false'
This makes sure the hook_plugin() will run
=> Fix checking of requirements for plugin dependencies

classes/controller/blocks/class-media-controller.php
Ref: https://jira.greenpeace.org/browse/PLANET-3599
=> PLANET-3599 - Replace youtube url wth privacy-enhanced domain

classes/controller/blocks/class-controller.php, classes/controller/blocks/class-counter-controller.php, classes/controller/blocks/class-gallery-controller.php, planet4-blocks.php
Ref: https://jira.greenpeace.org/browse/PLANET-3593
=> PLANET-3593 - Allow blocks in posts

classes/class-loader.php, classes/controller/blocks/class-controller.php, classes/controller/blocks/class-newcovers-controller.php, classes/controller/blocks/class-submenu-controller.php, composer.json, tests/bootstrap.php
Update WordPress coding standards to 2.1 and fix violations
Update PHP_CodeSniffer to 3.4
=> Update code sniffer and WordPress code standards

README.md, composer.json
Add composer scripts for php code sniffer and php code beautifier
Update README
=> Add composer scripts for php code sniffer

classes/controller/menu/class-settings-controller.php, includes/settings.twig
[Jira Issue](https://jira.greenpeace.org/browse/PLANET-3656)
Fix submenu name and fix page description to make it less confusing for admins
=> Fix submenu name and page description

classes/controller/blocks/class-submenu-controller.php
Hide submenu block in campaigns posts
=> PLANET-3741 Hide submenu block in campaigns

classes/controller/blocks/class-cookies-controller.php
Change description fields in Cookies block into textarea type.
=> Planet 3728 cookies descriptions textarea

classes/controller/blocks/class-articles-controller.php, classes/controller/blocks/class-carouselheader-controller.php, classes/controller/blocks/class-columns-controller.php, includes/blocks/articles.twig, includes/blocks/carousel_header_full-width-classic.twig, includes/blocks/carousel_header_zoom-and-slide-to-gray.twig, includes/blocks/columns.twig, includes/blocks/columns_tasks.twig
- New tab functionality added to Columns, Articles and Carousel blocks
=> PLANET-2101 Blocks: Allow Editor to control link behaviour

classes/controller/menu/class-blocks-usage-controller.php
This PR adds the ID's of posts/tags for better support of editors
Also wraps the ID+title in a table for better readability
=> Improve blocks report

admin/js/admin.js, admin/js/blocks-admin.js, admin/js/cookies.js
Ref: https://jira.greenpeace.org/browse/PLANET-3638
=> PLANET-3638 - JS: Use the same closure method for all js code

classes/controller/blocks/class-columns-controller.php, includes/blocks/columns.twig, includes/blocks/columns_tasks.twig
- Make title not compulsory.
- Make body and image compulsory for task to appear (as requested by design).
=> PLANET-3825 remove compulsory header

classes/controller/blocks/class-columns-controller.php, includes/blocks/columns.twig, includes/blocks/columns_tasks.twig
Apply new specs for displaying columns in Columns block.
Header or Body need to be filled in order for a column to appear.
=> PLANET-3902 columns new specs

classes/controller/menu/class-blocks-usage-controller.php, planet4-blocks.php, tests/bootstrap.php
Escape table names in various sql queries
=> PLANET-4005 Fix rips warnings

classes/controller/blocks/class-takeactionboxout-controller.php
- added args to query to order select act page dropdown list
=> PLANET-4024 Take Action boxouts: Order pages alphabetically 

classes/controller/blocks/class-takeactionboxout-controller.php
- Allowed Take Action Boxout Block in posts
- Add legend to inform editors not to add more than one block
=> PLANET-4023 Allow "Take Action" boxout in Posts 

classes/controller/blocks/class-takeactionboxout-controller.php
- Added placeholder meta data to Select2 dropdown to fix unresponsive clearing of selection
=> PLANET-4023 fix unresponsive select2 dropdown on clearing selection

classes/controller/blocks/class-takeactionboxout-controller.php
- returns empty array if act page no longer published
=> PLANET-4062 TA Box not disappearing

classes/controller/blocks/class-counter-controller.php
- added transient variable to keep counter value consistent.
=> PLANET-4082 CPP - Incorrect and inconsistent counter numbers
